//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkCrud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public long ReferenciaArticulo { get; set; }
        public string NombreArticulo { get; set; }
        public int CantidadArticulo { get; set; }
        public int ValorArticulo { get; set; }
    }
}
